Repository GLO2003-H22-eq24/Floppa, pull requests merged in 2022-04, with the labels that each got.

#147 Rédaction du COC en markdown
  CodeOfConduct.md
Labels: Code Of Conduit

#162 Tp4.md documentation
  README.md
  exercices/Screenshots/TP4/CodeQLScreen1.png
  exercices/Screenshots/TP4/CodeQLScreen2.png
  exercices/Screenshots/TP4/Sonar1.png
  exercices/Screenshots/TP4/arbre.png
  exercices/Screenshots/TP4/badgeReadMe.png
  exercices/Screenshots/TP4/issues1.png
  exercices/Screenshots/TP4/issues2.png
  exercices/Screenshots/TP4/issues3.png
  exercices/Screenshots/TP4/milestone.png
  exercices/Screenshots/TP4/pr1.png
  exercices/Screenshots/TP4/pr2.png
  exercices/Screenshots/TP4/pr3.png
  exercices/Screenshots/TP4/projet.png
  exercices/Screenshots/TP4/sonar2.png
  exercices/Screenshots/TP4/sonar3.png
  exercices/tp4.md
Labels: documentation

#152 Create LICENSE
  LICENSE
Labels: documentation

#154 Rédaction du ContibutionBestPractices en markdown
  CONTRIBUTING.md
Labels: documentation, Open Source

#161 Code smells
  .github/pull_request_template.md
  .run/All in floppa.run.xml
  src/main/java/ulaval/glo2003/floppa/seller/domain/Seller.java
  src/main/java/ulaval/glo2003/floppa/seller/repository/mongo/SellerRepositoryMongo.java
  src/test/java/ulaval/glo2003/floppa/app/domain/DateUtilTest.java
  src/test/java/ulaval/glo2003/floppa/offers/applicative/OffersServiceTest.java
  src/test/java/ulaval/glo2003/floppa/product/domain/ProductTest.java
Labels: Clean Code

#163 Updated prep open source
  exercices/tp4.md
Labels: documentation

#167 Dev
  .github/pull_request_template.md
  .run/All in floppa.run.xml
  .run/FloppaRunnable.run.xml
  .run/FloppaRunnableProd.run.xml
  CONTRIBUTING.md
  CodeOfConduct.md
  LICENSE
  README.md
  exercices/Screenshots/TP4/CodeQLScreen1.png
  exercices/Screenshots/TP4/CodeQLScreen2.png
  exercices/Screenshots/TP4/Sonar1.png
  exercices/Screenshots/TP4/arbre.png
  exercices/Screenshots/TP4/badgeReadMe.png
  exercices/Screenshots/TP4/issues1.png
  exercices/Screenshots/TP4/issues2.png
  exercices/Screenshots/TP4/issues3.png
  exercices/Screenshots/TP4/milestone.png
  exercices/Screenshots/TP4/pr1.png
  exercices/Screenshots/TP4/pr2.png
  exercices/Screenshots/TP4/pr3.png
  exercices/Screenshots/TP4/projet.png
  exercices/Screenshots/TP4/sonar2.png
  exercices/Screenshots/TP4/sonar3.png
  exercices/Screenshots/arbre/img.png
  exercices/tp4.md
  src/main/java/ulaval/glo2003/floppa/product/api/ProductResource.java
  src/main/java/ulaval/glo2003/floppa/product/applicative/ProductService.java
  src/main/java/ulaval/glo2003/floppa/seller/domain/Seller.java
  src/main/java/ulaval/glo2003/floppa/seller/repository/mongo/SellerRepositoryMongo.java
  src/test/java/ulaval/glo2003/floppa/app/domain/DateUtilTest.java
  src/test/java/ulaval/glo2003/floppa/offers/applicative/OffersServiceTest.java
  src/test/java/ulaval/glo2003/floppa/product/api/ProductResourceAddViewITTest.java
  src/test/java/ulaval/glo2003/floppa/product/domain/ProductTest.java
Labels: documentation, Enhancement, Clean Code
